import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import { api } from "~/utils/api";
import Image from "next/image";
import Layout from "~/components/Layout";

const Product: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const { data: product } = api.product.getOne.useQuery(id as string);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex min-h-screen bg-neutral-100 p-12">
          <div className="mx-auto flex w-[1240px] flex-col items-center gap-8 ">
            {product && (
              <>
                <div className="mx-auto flex rounded-xl bg-neutral-50 drop-shadow-xl">
                  <Image
                    width="640"
                    height="480"
                    src={product.image}
                    alt="product"
                    className="rounded"
                  />
                  <div className="flex flex-col gap-4 p-8">
                    <div className="flex items-center justify-between">
                      <h2 className="text-2xl font-bold">{product.title}</h2>

                      <span className="ml-auto text-lg font-medium">
                        ${product.price}
                      </span>
                    </div>
                    <div className="flex items-center  justify-between  gap-4">
                      <div className="flex items-center  gap-2">
                        <Image
                          width={64}
                          height={64}
                          src={product.user?.image as string}
                          alt="seller"
                          className="h-[32px] w-[32px] rounded-full object-contain"
                        />
                        <span>{product.user?.name}</span>
                      </div>
                      <span>{product.quantity} still in stock</span>
                    </div>
                    <p className="whitespace-pre-line">{product.description}</p>
                    <div className="flex items-center gap-4">
                      <button className="w-fit rounded bg-amber-300 py-2 px-4 font-medium">
                        ADD TO CART
                      </button>
                      <button className="ouline-1 w-fit rounded bg-amber-100 py-2 px-4 font-medium text-amber-900 outline outline-1 outline-amber-300">
                        BUY NOW
                      </button>
                    </div>
                  </div>
                </div>
                <ul className="flex flex-col gap-8">
                  {product.ratings.map((rating) => {
                    return (
                      <li key={rating.id}>
                        <div className="rounded-xl bg-neutral-50 p-8 drop-shadow-xl">
                          <div className="flex justify-between">
                            <h4 className="text-lg font-bold">
                              {rating.title}
                            </h4>
                            <div className="flex items-center gap-2">
                              <Image
                                width="128"
                                height="128"
                                src={rating.user.image || ""}
                                alt="rating author"
                                className="h-8 w-8 rounded-full bg-neutral-50 shadow-inner"
                              />
                              <div className="text-md font-medium">
                                {rating.user.name}
                              </div>
                            </div>
                          </div>
                          <p className="text-md px-2 pt-2">{rating.message}</p>
                        </div>
                        <span className="text-md float-right mt-4 font-light">
                          {rating.createdAt.toLocaleDateString()}
                        </span>
                      </li>
                    );
                  })}
                </ul>
              </>
            )}
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Product;
