import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";
import Link from "next/link";
import Layout from "~/components/Layout";

const Home: NextPage = () => {
  const { data: products } = api.product.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex min-h-screen flex-col bg-neutral-100 ">
          <ul className="flex flex-wrap justify-center gap-12 p-12 max-w-[2560px] mx-auto">
            {products &&
              products.map((product) => {
                return (
                  <Link key={product.id} href={`/product/${product.id}`}>
                    <li className="mx-auto h-[500px] w-[410px] overflow-hidden rounded-xl bg-neutral-50 drop-shadow-md">
                      <Image
                        src={product.image}
                        width="1160"
                        height="870"
                        placeholder="blur"
                        blurDataURL={product.smallImage}
                        alt="product image"
                      />
                      <div className="overflow-hidden p-6">
                        <div className="text-lg font-bold">{product.title}</div>
                        <div className="text-md  max-h-[80px] overflow-hidden whitespace-pre-line font-light">
                          {product.description}
                        </div>
                        <div className="mt-3 flex items-center justify-between px-2">
                          <div className="flex items-center gap-3">
                            <Image
                              width={32}
                              height={32}
                              src={product.user?.image as string}
                              alt="seller"
                              className="h-[32px] w-[32px] rounded-full object-contain"
                            />
                            <span>{product.user?.name}</span>
                          </div>
                          <span className="font-semibold">
                            ${product.price}
                          </span>
                        </div>
                      </div>
                    </li>
                  </Link>
                );
              })}
          </ul>
          <div className="flex flex-col items-center gap-2"></div>
        </main>
      </Layout>
    </>
  );
};

export default Home;
