import { type NextPage } from "next";
import Head from "next/head";
import Input from "~/components/Input";
import { useForm } from "react-hook-form";
import { api } from "~/utils/api";
import { zodResolver } from "@hookform/resolvers/zod";
import { signUpSchema, type SignUpFields } from "~/schemas/signUp";
import Link from "next/link";

const SignUp: NextPage = () => {
  const form = useForm<SignUpFields>({
    mode: "all",
    resolver: zodResolver(signUpSchema),
  });

  const { handleSubmit } = form;

  const createUser = api.user.create.useMutation({});

  const onSubmit = (data: SignUpFields) => {
    console.log("submit: ", data);
    createUser.mutate(data);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-neutral-100">
        <form
          onSubmit={(...args) => void handleSubmit(onSubmit)(...args)}
          className="flex min-w-[360px] flex-col gap-6 rounded-lg bg-neutral-50 p-8 text-slate-900 drop-shadow-lg"
        >
          <h2 className="text-center text-xl font-bold">Sign Up</h2>
          <p className="text-md font-rg text-center">
            please fill in the fields below
          </p>
          <Input
            name="name"
            label="Username"
            type="text"
            placeholder="John Smith"
            form={form}
          />
          <Input
            name="email"
            label="E-Mail"
            type="email"
            placeholder="jsmith@gmail.com"
            form={form}
          />
          <Input
            name="password"
            label="Password"
            type="password"
            placeholder="••••••••"
            form={form}
          />
          <Input
            name="confirmPassword"
            label="Confirm Password"
            type="password"
            placeholder="••••••••"
            form={form}
          />

          <div className="flex flex-col items-center gap-3">
            <button
              type="submit"
              className="w-full rounded bg-blue-400 p-3 font-semibold  text-slate-50"
            >
              SUBMIT
            </button>
            <span className="">
              Already have an account?{" "}
              <Link href="/api/auth/signin" className="text-blue-400">
                sign in
              </Link>
            </span>
          </div>
        </form>
      </main>
    </>
  );
};

export default SignUp;
